version: '3.7'

services:
  db:
    image: postgres:11
    container_name: db
    ports:
      - 5430:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
