server:
  port: 8085
  servlet:
    context-path: /business
spring:
  application:
    name: business
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5430/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
  command:
    sendRespond:
      circuitBreaker:
        requestVolumeThreshold: 30
  default:
    circuitBreaker:
      sleepWindowInMilliseconds: 4000
