server:
  port: 8083
  servlet:
    context-path: payment-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}lication
spring:
  application:
    name: PAYMENT
