spring:
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
server:
  port: 8088
