server:
  port: 8077
spring:
  application:
    name: crm
  main.allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5430/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#      temp:
#        use_jdbc_metadata_defaults: false
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      format_sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}
